### ISSUE TITLE
S-58 Check 1795a & 1795b

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#21]
Check 1795a & 1795b

Proposal from Nautical Dimensions for a new checks 1795c, 1795d, 1795e and 1795f to check for slave objects that do not have temporal attributes encoded where the master object does.

[S58-Check 1795a & b.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116633/S58-Check.1795a.b.docx)

**Comment by FrankHippmann** [comment]
Agree

**Comment by IngaFjellanger** [comment]
Navico agrees

**Comment by alvarosanuy** [comment]
Supported

**Comment by TomRichardson6** [comment]
Agree

**Comment by JeffWootton** [comment]
Agree.  However, could this be achieved by adding some words to Checks 1795a and b?  This would save adding 4 new Checks if it is logical.  Amendments in bold italics (note also some other syntax changes also in bold italics - I think the "or" in these cases is not a operation):

1795a:  For each feature object which is a slave in a Master to Slave relationship AND where DATSTA or PERSTA attributes are notNull _**for both the master and slave object**_ AND the values of DATSTA **_or_** PERSTA are Less than the values of DATSTA **_or_** PERSTA encoded on the master object.

1795b:  For each feature object which is a slave in a Master to Slave relationship AND where PEREND **_or_** DATEND attributes _**for both the master and slave object**_ are notNull AND the values of PEREND **_or_** DATEND are Greater than the values of PEREND **_or_** DATEND encoded on the master object.

**Comment by Christian-Shom** [comment]
Agree with the proposal.
Like Jeff, agree it would be nice not to add 4 more checks, but I'm not sure Jeff's wording works ("attributes for both the master and slave object" needn't be both notNull).

**Comment by FrankHippmann** [comment]
I don't think you can easily combine 1795a and 1795b with the proposed 1795c, 1795d, 1795e and 1795f. The purpose of 1795a and 1795b is to compare the values of the date attributes for master and slave. The proposed checks cater for the scenario where the master defines a date attribute, but the slave doesn't.

I proposed four new checks so that the wording of each is succinct and unambiguous. I personally favour a greater number of  checks if it means that you reduce the complexity of each individual check. Having said that, you could potentially reduce the four proposed checks down to one:

_For each feature object which is a slave in a Master to Slave relationship AND where DATSTA, DATEND, PERSTA or PEREND is notNull on the master object AND the corresponding DATSTA, DATEND, PERSTA or PEREND is Not Present or Null on the slave object._

I agree with Jeff that the highlighted "or" occurrences  in 1795a and 1795b should be lower case.

**Comment by LARRIVEEJCANADA** [comment]
Not agree as there is not existing child without any parent.  The intend is to not have to code in duplication.  This is taking in charge by the parent object.  As we MUST create the relashionship still, this is taking in charge.
