### ISSUE TITLE
S-58 Check 2000 - VERDAT

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#23]
Proposal from Nautical Dimensions  (see ENCWG4-05.11) 

It is recommended that the values for DSPM/VDAT, M_VDAT/VERDAT, the VERDAT
attribute of features other than M_SDAT and the DSID.SDAT, be constrained in line with the constraints stated in the S-101 DCEG and the S101 Feature Catalogue
[ENCWG4_2019_5.11_EN_Consistent Use of Vertical Reference Datums in ENCs_V1.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116666/ENCWG4_2019_5.11_EN_Consistent.Use.of.Vertical.Reference.Datums.in.ENCs_V1.pdf)
[S58-Check 2000 - VERDAT.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116670/S58-Check.2000.-.VERDAT.docx)

**Comment by FrankHippmann** [comment]
Agree

**Comment by FrankHippmann** [comment]
The following document is the equivalent of check 2000 VERDAT for DSPM.VDAT and DSPM.SDAT. This recommendation goes hand in hand with the check 2000 VERDAT recommendation.

[New check for constrained values of DSPM.VDAT and DSPM.SDAT.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5242615/New.check.for.constrained.values.of.DSPM.VDAT.and.DSPM.SDAT.docx)

**Comment by alvarosanuy** [comment]
AUOC 4.2.0 section 2.1.3 Sounding Datum Table 2.2 includes 'International Great Lakes datum 1985 (Id=25)'.
Shouldn't this value be included as a valid option in the proposed checks for M_SDAT and the SDAT subfield of the DSPM field ?

**Comment by TomRichardson6** [comment]
Agree but support including value 25 for SDAT as Alvaro proposes.

**Comment by JeffWootton** [comment]
Agree with both proposals and support the addition of value 25 for M_SDAT and SDAT.

**Comment by Christian-Shom** [comment]
Agree and supports addition of value 25.

**Comment by IngaFjellanger** [comment]
Navico agrees. We also supports including value 25

**Comment by LARRIVEEJCANADA** [comment]
Agree and supports addition of value 25.

**Comment by JeffWootton** [comment]
Noting the decision of the Sub-Group meeting (01/12/20) to include a new Check 1504b:  I think this now makes the (newly renamed) Check 1504a redundant.  As Null is not included in the allowable list in 1504b, a Null value will fail this Check.  I therefore suggest that the agreed on new Check 1504b **replaces** the existing Check 1504, rather than supplements.

Noting the decision of the Sub-Group meeting (01/12/20) to include a new Check 1510b:  I think this now makes the (newly renamed) Check 1510a redundant.  As Null is not included in the allowable list in 1510b, a Null value will fail this Check.  I therefore suggest that the agreed on new Check 1510b **replaces** the existing Check 1510, rather than supplements.

**Comment by Richard-Fowle** [comment]
Agree
