### ISSUE TITLE
S-58 New Check to identify where M_COVR is modified by an ER file

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#27]
Proposal from UKHO (ENCWG Chair)
Whilst reviewing critical error checks in S-58 we came across a mandatory requirement in S-57 that is not tested for and can cause gaps and overlaps in data. Both S101 and S57 state that M_COVR should not be modified by update. We have fallen foul of this omission from S-58 and consequently released numerous cells to market that introduced overlaps and gaps in ENC coverage. 
[New S58-Check M_COVR.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116850/New.S58-Check.M_COVR.docx)

**Comment by FrankHippmann** [comment]
Agree

**Comment by alvarosanuy** [comment]
Agree

**Comment by TomRichardson6** [comment]
Agree note that some validation tools already provide this check.

**Comment by Christian-Shom** [comment]
Agree and suggest upgrading to CRITICAL.

**Comment by IngaFjellanger** [comment]
We agree that such check is needed but we disagree with wording of the proposed check. 
Normally what happens in the cases where an M_COVR is updated by an updated. is that there is no reference to M_COVR in the update file.
The check must trigger if a dataset update contains instructions to modify position of spatial objects that are referred by M_COVR with CATCOV =1 or this object refers to other spatial objects with a new position.
We suggest the following wording of the 1024c check:
For each ER file which contains instructions to modify the extent of M_COVR object with CATCOV =1.

**Comment by JeffWootton** [comment]
Agree with Inga's comment; and also agree to classify as Critical.

**Comment by Christian-Shom** [comment]
Agree with Inga's comment and wording.
Suggest to change the Check solution for: "Modify the update so that data coverage is not changed, or issue a New Edition."

**Comment by LARRIVEEJCANADA** [comment]
Agree to add this check and upgrade to Critical as well.

**Comment by FrankHippmann** [comment]
Due to how chain-node topology is encoded, modifying the geometry linked to an M_COVR is often a necessary part of an update. When a feature that extends beyond the cell boundary is added, a connected node is inserted where that feature meets the boundary of the M_COVR. Therefore, adding or removing features in an update can cause edges referenced by an M_COVR to be either split or merged. So the geometry linked to the M_COVR can technically change, however the extents should remain equal to that of the base cell within an acceptable tolerance. 

We could base the tolerance on COMF, but this would result in a critical error being reported whenever a point of an updated M_COVR is situated only 1 cm (ground units) away from the boundary of the original M_COVR (assuming a COMF of 10 power 7). This could result in a multitude of datasets producing critical errors for a scenario that is imperceptible at any standard dataset scale. I would prefer a tolerance based on the dataset scale, e.g. 0.1 mm at scale (roughly 1/2 the size of a display pixel).

The original wording of the proposal is fine with me, but perhaps a note regarding tolerance is required.

I suggest that at least three more test datasets be added to the S-58 Critical Test Datasets.

**Test Dataset 1**

An update where

(a)	a feature is added that meets the M_COVR boundary, resulting in a new connected node and an edge being split.
(b)	a feature that meets the M_COVR boundary is removed, resulting in the removal of a connected node and the two linked edges being merged.

This update does not alter the extents of the M_COVR beyond the tolerance. No critical error is to be reported.

**Test Dataset 2**
An update where the M_COVR extents are increased slightly beyond the tolerance. A critical error is to be reported.

**Test Dataset 3**
An update where the M_COVR extents are decreased slightly beyond the tolerance. A critical error is to be reported.

**Comment by Christian-Shom** [comment]
Agree to take the scale of the ENC into account. However, as it is possible that some HOs do not use a COMF value of 10 power 7 for all their ENCs (this is not mandatory), rather than mm at scale, I would suggest a tolerance of 2 COMFs. 
The only possible (although unlikely) issue I see is that this could allow overlaps of more than 5 metres on the ground (see UOC 2.1.8) between ENCs having a COMF value of 10 power 4. Not sure this would be a real problem.

**Comment by Richard-Fowle** [comment]
New check 1024c added

**Comment by Richard-Fowle** [comment]
New check 1024c added to edition 7.0.0
