### ISSUE TITLE
S-58 New check to identify objects tagged as both a master and as a slave

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#28]
Proposal from SHOM
I suggest to create (for next edition of S-58) a new check to detect an object that would be slave and master.
I have found nothing against this in the Product Specification, but in the UOC (§12.1.2) we have:
"A slave object must not be related to more than one master object, and an object must not be both a master and a slave object."

[New S58-Check Object both M&S.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116870/New.S58-Check.Object.both.M.S.docx)

**Comment by FrankHippmann** [comment]
Agree

**Comment by IngaFjellanger** [comment]
Navico agrees

**Comment by alvarosanuy** [comment]
Agree

**Comment by TomRichardson6** [comment]
Agree

**Comment by JeffWootton** [comment]
Agree

**Comment by JeffWootton** [comment]
Agree

**Comment by TDYCARHugh** [comment]
I agree based on what the UOC is currently saying but I am curious about the following theoretical situation.
I recall someone describing a large light on a structure where the light was large enough that another object such as a fog signal or radio antenna was mounted on the light.  In such a case would the light be considered both equipment and a structure or would the devices mounted on the light be considered equipment onto the base structure?
Given what the UOC is saying I guess the encoding would have to be that all the equipment objects would be considered to be on the main structure regardless of whether they are physically mounted on top of one another.

**Comment by alvarosanuy** [comment]
For me all this is about logical consistency and the truth is that, irrespective of what we choose as master or slave, it will not have any impact on ECDIS display of performance.

I disagree this particular check has to be CRITICAL simply because there is a 'must' in the document of reference.
S-58 section 1.2 is clear about the criteria to use to allocate a check's severity. The impact on the user has to be the overriding factor for consideration. This fundamental principle must be discussed by this forum as some comments have been added to other Issues recommending not to classify new checks as CRITICAL or ERROR simply because they do not have  'must' in the document. This despite that particular scenario having the potential to negatively impact the usability or clarity of a product.

**Comment by LARRIVEEJCANADA** [comment]
Agree with this proposal, no matter the way,  it should be:  encoding practice have have to be that all the equipment objects would be considered to be on the main structure regardless of whether they are physically mounted on top of one another.
