### ISSUE TITLE
S-58 Checks 54a, 54b, 54c & 1775 

### ISSUE THREAD

**Issue by iho-ohi** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#3]
Proposals from IC-ENC and AHO (ENCWG4-5-17) Add MORFAC as an acceptable underlying feature object for a DAYMAR
[S58-Check 54 a,b&c.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5108602/S58-Check.54.a.b.c.docx)
[S58-Check 54b & 1775.docx](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5108603/S58-Check.54b.1775.docx)
[ENCWG4_2019_5.17_DAYMAR and the double encoding of Base display objects_FINAL.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5108609/ENCWG4_2019_5.17_DAYMAR.and.the.double.encoding.of.Base.display.objects_FINAL.pdf)
[ENCWG5_2020_11F_DAYMAR_and_the_double_encoding_of_Base_display_objects_FINAL.pdf](https://github.com/iho-ohi/ENCWG-S58-ENC-Validation-Checks/files/5116318/ENCWG5_2020_11F_DAYMAR_and_the_double_encoding_of_Base_display_objects_FINAL.pdf)

**Comment by FrankHippmann** [comment]
I suppose a DAYMAR could be made a slave to the MORFAC. However, I agree that this shouldn’t be a critical error.

**Comment by alvarosanuy** [comment]
Support all proposals.

**Comment by Christian-Shom** [comment]
Agree with all the proposals.

**Comment by JeffWootton** [comment]
Do not agree with the proposed changes to 54a and 54c.  For 54a, it is not logical that a fortified structure, landmark or silo/tank would be “situated on” a dolphin, deviation dolphin or post/pile (if that post/pile had the main purpose as a mooring facility).  For 54c, it is not logical that a building or crane would be “situated on” a dolphin, deviation dolphin or post/pile (if that post/pile had the main purpose as a mooring facility).  When encoding object classes for ENC, the principal purpose for the existence of the real-world feature should drive the object class used to encode that feature.  I fail to see how the principal purpose for any structure that supports any of the above features could be said to be performing the principal role of a mooring facility.

I think a similar argument applies to 54b, in that (a) I think it would be difficult to moor up to a dolphin or deviation dolphin if it had a daymark sitting on it; and (b) if a post/pile has a daymark on it, I would question whether its principal purpose is that of a mooring facility or an aid to navigation, and as such should be encoded as PILPNT rather than MORFAC.

Agree with the logic around downgrading Check 54b from C to W, and also the proposed change to Check 1775.  Additionally suggest that, as for Check 54a, Check 54c is upgraded to Critical.

**Comment by Christian-Shom** [comment]
After Jeff's comments:
I agree in principle with his comments on the logical 54a. Yet, the current check already allows "exotic" encodings like "a FORSTC on a PONTON" or "a SILTNK on a HULKES". If I understand correctly, the reason of the "C" check is to trigger when "dangerous" object ly in the water but are not covered by a Display Base object. So, to avoid a Critical, I see no other option than the one suggested by the proposal.
