### ISSUE TITLE
Too many vertices in an exchange set.

### ISSUE THREAD

**Issue by richardsonaz** [iho-ohi/ENCWG-S58-ENC-Validation-Checks#52]
The UKHO has found older versions of Transas and SAM ECDIS to crash when importing exchange sets that contain too many vertices. These align to checks 99,100 and 101 in S-58 v7. I believe these are currently set to Error but we believe these should be changed to critical as these older OEM systems are still in use today and not being able to load data is a safety concern.

**Comment by Christian-Shom** [comment]
S-57 Part 3 §2.7 states that "_The only size restriction is a maximum field length of 109-1 bytes which is defined by ISO/IEC 8211_". 
I guess this is where validation checks 99, 100 and 101 come from. They therefore should be "Critical" in theory.

However, there might be a huge number of ENCs that trigger these checks, in which case making them "critical" would have a dramatic impact for many data providers.

Do we have the list of ENCs that cause this issue? This may help find a solution, or at least understand the origin of the problem.

**Comment by Christian-Shom** [comment]
As a complement:
we have created a DEPCNT object with only one edge and containing more than 20 000 coordinates.
We have checked the ENC with dKart Inspector and 7Cs Analyzer and don't have any error on check 100, which is surprising...
Unless we have made a mistake somewhere, I wonder if checks 99, 100 and 101 are implemented in the validation tools.

**Comment by kusala9** [comment]
I think (and I might be wrong!) that one of the issues seen with these systems is when the 8211 record size exceeds 99999 bytes in total. This was definitely a problem with some older systems. The first 5 bytes of the 8211 record denote the size of the entire record. If the record is over 99999 bytes (if there are a large number of vertices for example) the system should use the size of each field to calculate the record size before proceeding - in these cases the first 5 bytes of the 8211 record are set to 00000. 

This used to be a problem with import of large exchange sets with a lot of entries because the CATD record in the CATALOG.031 would grow very large but it could equally apply to a record defining a curve with a LOT of vertices.

The restriction on a field length of 10^9-1 bytes is because the field width in the DDR in 8211 is a single digit, so the largest field you can represent has 999,999,999 bytes in it (hence the restriction). that would be 50 million vertices (8 bytes per coordinate pair I guess) which I think we're probably comfortably within. I'm aware of lots of cases of the first issue, not so many of the second. @Richard-Fowle will remember this I think.

**Comment by FrankHippmann** [comment]
The limits specified by S-58 checks 99, 100 and 101 are crude estimates, and there are other factors that determine the size of a record.

I would like to propose a rewording and consolidation of the checks, since the checks as they are can produce errors for datasets that don't exhibit this problem (failure to import into some ECDIS). The core reason for this check is to identify datasets containing records having greater than 99999 bytes. Counting the number of coordinates, geometry references, etc. is only an inaccurate measure of this. The problem can be identified much more simply, that is, whenever a record contains more than 99999 bytes, the record length in the DR leader is set to "00000". So the three checks can be replaced by a single check.

**Check description:** For each ISO 8211 record where the Record Length specified by the DR Leader is equal to "00000".

**Check message:** DR Leader Record Length is set to "00000"

**Check solution:** Split or optimise record.

Even though an error is reported, the ISO 8211 data is still valid in this case. It is just that some ECDIS systems cannot load this data.

The latest version of 7Cs Analyzer will report on such instances. If the dataset in question can be provided, I can have a look and investigate the cause of the issue.

**Comment by Richard-Fowle** [comment]
At the VTC of ENCWG S-58 SubWG It was agreed that these checks could be upgraded to 'Critical' considering the impact on some older ECDIS systems. UKHO will add a remark to their response to IHO CL30/2024
